# Generated by Django 6.0 on 2026-02-12 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Use the first day of the month (e.g. 2026-02-01)')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_fees', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('student', 'month')},
            },
        ),
    ]
