# Generated by Django 6.0 on 2026-02-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_monthlyfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_fee_amount', models.DecimalField(decimal_places=2, default=1000, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='monthlyfee',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
