# Generated by Django 6.0 on 2026-01-05 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinsight',
            name='cluster',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='message',
            field=models.TextField(default='AI analysis pending. More data required.'),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insight', to='students.studentprofile'),
        ),
    ]
