# Generated by Django 6.0 on 2026-01-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_alter_aiinsight_cluster_alter_aiinsight_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='status',
            field=models.CharField(default='Analysis Pending', max_length=50),
        ),
    ]
