# Generated by Django 6.0 on 2026-01-02 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningdocument',
            name='student',
        ),
        migrations.AlterField(
            model_name='learningdocument',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='instructors.instructorprofile'),
        ),
    ]
