# Generated by Django 6.0 on 2026-01-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_remove_learningdocument_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
